### ISSUE TITLE
Check coding standards with latest version of WP coding standards

### ISSUE THREAD

**Issue by iruzevic** [infinum/coding-standards-wp#27]
I have an error when using latest version of our standards. 0.4.1.

```FILE: src/blocks/class-blocks.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: Trying to access array
   |       | offset on value of type bool in
   |       | /Users/ruzevic/projects/infinum/eightshift-libs/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php
   |       | on line 1252 (Internal.Exception)
----------------------------------------------------------------------```

**Comment by isaaclubow** [comment]
Same - `An error occurred during processing; checking has been aborted. The error message was: Trying to access array offset on value of type bool in ~/.composer/vendor/wpcs/WordPress/Sniff.php on line 1337`

**Comment by 11digitlabs** [comment]
I have the same issue. Is there any workarounds? Fixes?

Thanks a lot!

**Comment by dingo-d** [comment]
Latest version should be working, I think I updated all the dependencies, but I'll have to give it a closer look. Temporary workaround is to use version 0.4.

**Comment by 11digitlabs** [comment]
Alright! Thanks a lot for the heads up

**Comment by dingo-d** [comment]
This should be fixed with the latest version
