### ISSUE TITLE
Add variable in esc string

### ISSUE THREAD

**Issue by iruzevic** [infinum/coding-standards-wp#6]
Please check the ability to add a global variable to escaped string as a package. 

<img width="838" alt="screen shot 2018-01-26 at 10 29 07" src="https://user-images.githubusercontent.com/23283324/35433851-2df41ad4-0285-11e8-9e50-6fe165e58212.png">

**Comment by dingo-d** [comment]
https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/
